### ISSUE TITLE
[FEAT] 리뷰 작성, 유저 리뷰 조회 화면 폴더구조, css 수정

### ISSUE THREAD

**Issue by yunii23** [1-MSG/frontend#37]
---

**기능 설명**

- [x] 리뷰 작성 화면 css 수정

- [x] 유저 리뷰 조회 화면 css 수정

- [x] product-review 폴더 구조 변경

- [x] 리뷰 화면 내 필요한 svg 추가

**추가 설명**

- (products)/product-detail/[productId]/page.tsx 변경 사유: 리뷰 화면과 공통적으로 사용하던 png를 svg로 변경하면서 해당 페이지 부분에서 사용하던 것은 제거함
- 추후 별점 구현하면 해당 화면들 완료

**Comment by YOON-CC** [comment]
확인했습니다!
